import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React from 'react';

import impactImg from '../public/home/impact.svg';
import logoImg from '../public/heliosdao-logo.png';
import monitorImg from '../public/home/monitor.svg';
import powerImg from '../public/home/power.svg';
import profitImg from '../public/home/profit.svg';
import returnsImg from '../public/home/returns.svg';
import tokensImg from '../public/home/tokens.svg';
import transparencyImg from '../public/home/transparency.svg';
import votesImg from '../public/home/votes.svg';
import imgProject1 from '../public/home/project1.png';
import imgProject2 from '../public/home/project2.png';

const Home: NextPage = () => {
  return (
    <div className="bg-white font-sans">
      <Head>
        <title>HeliosDAO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className='flex justify-between py-4 px-8'>
        <div>
          <Image src={logoImg} width={52} height={46} />
        </div>
       <nav className="text-lg font-serif">
          <a href='#'>Invest</a>
        </nav>
      </header>

      <main className="">
        <div className="max-w-2xl mx-auto text-center pt-44 pb-36">
          <h1 className="font-serif text-7xl mb-4">
            Invest Crypto.<br/>
            Fund Solar.<br/>
            Save Our Climate.
          </h1>

          <p className="mb-16 text-2xl">
            Stable crypto returns from real world solar projects around the globe.
          </p>

          <p>
            <a className="bg-yellow rounded-2xl py-2 px-4 text-xl display-inline-block" href=''>Start Investing</a>
          </p>
        </div>

        <div className='px-8'>
          <Image src={tokensImg} />
        </div>

        <div className='bg-gradient-to-b from-white to-light-yellow'>
          <div className="container max-w-screen-lg mx-auto pt-20 pb-16">
            <div className="flex gap-16 mb-24 items-center">
              <div className='basis-1/2'>
                <h3 className="font-serif text-5xl mb-3">Invest in Impact</h3>
                <p>Directly fund high impact solar projects reducing thousands of tonnes of CO2 emissions</p>
              </div>
              <div className="basis-1/2 text-center">
                <Image src={impactImg} width='200px' />
              </div>
            </div>
            <div className="flex gap-16 mb-24 items-center">
              <div className="basis-1/2 text-center">
                <Image src={transparencyImg} width='200px' />
              </div>
              <div className='basis-1/2'>
                <h3 className="font-serif text-5xl mb-3">Maximum Transparency</h3>
                <p>Track your money in real time, from placement to production to power generation</p>
              </div>
            </div>
            <div className="flex gap-16 mb-24 items-center">
              <div className='basis-1/2'>
                <h3 className="font-serif text-5xl mb-3">Industry Leading Returns</h3>
                <p>Investing in clean energy generates 15%+ APY, safe from the volatility of crypto markets</p>
              </div>
              <div className="basis-1/2 text-center">
                <Image src={returnsImg} width='200px' />
              </div>
            </div>
            <div className="flex gap-16 items-center">
              <div className="basis-1/2 text-center">
                <Image src={powerImg} width='200px' />
              </div>
              <div className='basis-1/2'>
                <h3 className="font-serif text-5xl mb-3">Power of Crypto</h3>
                <p>Borderless digital currency allows Helios to invest where big banks feat to tread.</p>
              </div>
            </div>
          </div>
        </div>

        <div className="container max-w-screen-lg mx-auto pt-20 pb-16">
          <h2 className="font-serif text-5xl text-center mb-16">How It Works</h2>
          <div className='flex mb-16 items-center'>
            <div className='basis-1/2 flex'>
              <p className="font-serif text-3xl pr-12">1</p>
              <div>
                <h3 className="font-serif text-2xl mb-2.5">Community Votes</h3>
                <p className='text-base'>The Helios community votes on which projects are added to Solar Pools based on Impact and Yield</p>
              </div>
            </div>
            <div className='basis-1/2 text-center'>
              <Image src={votesImg} width='300px' />
            </div>
          </div>
          <div className='flex mb-16 items-center'>
            <div className='basis-1/2 flex'>
              <p className="font-serif text-3xl pr-12">2</p>
              <div>
                <h3 className="font-serif text-2xl mb-2.5">Invest, Profit</h3>
                <p className='text-base'>Sunvestors provide capital to Solar Pools to fund real world solar projects and profit from the clean energy generated</p>
              </div>
            </div>
            <div className='basis-1/2 text-center'>
              <Image src={profitImg} width='300px' />
            </div>
          </div>
          <div className='flex mb-16 items-center'>
            <div className='basis-1/2 flex'>
              <p className="font-serif text-3xl pr-12">3</p>
              <div>
                <h3 className="font-serif text-2xl mb-2.5">Monitor Impact &amp; Returns</h3>
                <p className='text-base'>Monitor the progress of projects, energy produced, carbon offset, and returns in real time with our intuitive dashboard</p>
              </div>
            </div>
            <div className='basis-1/2 text-center'>
              <Image src={monitorImg} width='300px' />
            </div>
          </div>
        </div>

        <div className="bg-light-yellow py-16">
          <div className='container mx-auto'>
            <div className='text-center'>
              <h2 className='font-serif text-5xl mb-2'>Our Projects</h2>
              <p className='mb-12 max-w-sm mx-auto'>HeliosDAO works with experienced solar developers around the world to deploy capital into high impact, high return projects.</p>
            </div>
          </div>
          <div>
            <div className='relative overflow-hidden'>
              <div className='flex w-600 mx-auto'>
                <div className='px-10 min-w-full'>
                  <div className='bg-white border border-solid rounded-md border-slate-200'>
                    <Image src={imgProject1} />
                    <div className='py-7 px-9'>
                      <h3 className='font-serif text-4xl'>Project title</h3>
                      <p className='mb-6'>Uttar Pradesh, India</p>
                      <p>This is a little blurb about the project. It&apos;s really a nice bit of info that helps an investor understand what is going on with this project. Perhaps it links to a whole project page that shows you more detail on this project. This is a little blurb about the project. It&apos;s really a nice bit of info that helps an investor understand what is going on with this project. Perhaps it links to a whole project page</p>
                    </div>
                  </div>
                </div>
                <div className='px-10 min-w-full'>
                  <div className='bg-white border border-solid rounded-md border-slate-200 scale-75'>
                    <Image src={imgProject2} />
                    <div className='py-7 px-9'>
                      <h3 className='font-serif text-4xl'>Project title</h3>
                      <p className='mb-6'>Uttar Pradesh, India</p>
                      <p>This is a little blurb about the project. It&apos;s really a nice bit of info that helps an investor understand what is going on with this project. Perhaps it links to a whole project page that shows you more detail on this project. This is a little blurb about the project. It&apos;s really a nice bit of info that helps an investor understand what is going on with this project. Perhaps it links to a whole project page</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>

      <footer className='bg-dark-blue text-white'>
        <div className="container mx-auto flex justify-between py-16">
          <div>
            <p>&copy; HeliosDAO</p>
          </div>
          <div>
            <p className='text-right'>
              team@helios.eco<br />
              112 S Park St, San Francisco, CA 94107
            </p>
          </div>
        </div>
      </footer>
    </div>
  )
}

export default Home
